In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
# 파일 경로 리스트
file_paths = [
    "2021_delete_boarding_f.csv",
    "2022_delete_boarding_f.csv",
    "2023_delete_boarding_f.csv"
]

# 빈 데이터프레임 리스트 생성
dataframes = []

# 각 파일 불러오기
for file in file_paths:
    df = pd.read_csv(file)

    # 2023년도 데이터에서 '유형' 열 제거
    if '유형' in df.columns:
        df = df.drop(columns=['유형'])

    # 리스트에 추가
    dataframes.append(df)

# 모든 데이터프레임을 합치기
combined_df = pd.concat(dataframes, ignore_index=True)

# 합쳐진 데이터 확인
print(combined_df.head())

# 합쳐진 데이터를 CSV 파일로 저장
combined_df.to_csv("merged_boarding.csv", index=False)

                      접수일시                     예정일시                     배차일시  \
0  2021-01-01 02:25:24.000  2021-01-01 02:26:00.000  2021-01-01 02:35:36.000
1  2021-01-01 04:17:19.413  2021-01-01 04:17:19.413  2021-01-01 04:27:09.000
2  2021-01-01 04:41:40.000  2021-01-01 04:42:00.000  2021-01-01 04:50:36.000
3  2021-01-01 06:43:55.170  2021-01-01 07:00:00.000  2021-01-01 07:08:35.000
4  2021-01-01 07:23:14.143  2021-01-01 07:23:00.000  2021-01-01 07:28:32.000

                      승차일시                     하차일시 출발지구   출발지동 목적지구     목적지동  \
0  2021-01-01 02:56:15.000  2021-01-01 03:32:21.000  강서구  등촌제3동  종로구  종로5.6가동
1  2021-01-01 04:50:16.000  2021-01-01 04:58:55.000  노원구   중계4동  노원구     하계1동
2  2021-01-01 05:07:33.000  2021-01-01 05:53:06.000  강동구     길동  강서구      염창동
3  2021-01-01 07:14:17.000  2021-01-01 07:18:44.000  노원구   하계1동  노원구     하계1동
4  2021-01-01 07:35:23.000  2021-01-01 07:37:32.000  노원구   하계1동  노원구     하계1동

     요금     승차거리       대기시간  공휴일
0  3400  17553.0  30.850000    1
1  1500   2967.0  32.943117    1
2  4400  31641.0  25.883333    1
3  1500   1106.0  30.363833    1
4  1500    700.0  12.147617    1

In [ ]:
combined_df

,접수일시,예정일시,배차일시,승차일시,하차일시,출발지구,출발지동,목적지구,목적지동,요금,승차거리,대기시간,공휴일
0,2021-01-01 02:25:24.000,2021-01-01 02:26:00.000,2021-01-01 02:35:36.000,2021-01-01 02:56:15.000,2021-01-01 03:32:21.000,강서구,등촌제3동,종로구,종로5.6가동,3400,17553.0,30.850000,1
1,2021-01-01 04:17:19.413,2021-01-01 04:17:19.413,2021-01-01 04:27:09.000,2021-01-01 04:50:16.000,2021-01-01 04:58:55.000,노원구,중계4동,노원구,하계1동,1500,2967.0,32.943117,1
2,2021-01-01 04:41:40.000,2021-01-01 04:42:00.000,2021-01-01 04:50:36.000,2021-01-01 05:07:33.000,2021-01-01 05:53:06.000,강동구,길동,강서구,염창동,4400,31641.0,25.883333,1
3,2021-01-01 06:43:55.170,2021-01-01 07:00:00.000,2021-01-01 07:08:35.000,2021-01-01 07:14:17.000,2021-01-01 07:18:44.000,노원구,하계1동,노원구,하계1동,1500,1106.0,30.363833,1
4,2021-01-01 07:23:14.143,2021-01-01 07:23:00.000,2021-01-01 07:28:32.000,2021-01-01 07:35:23.000,2021-01-01 07:37:32.000,노원구,하계1동,노원구,하계1동,1500,700.0,12.147617,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156499,2023-12-31 21:32:12.433,2023-12-31 21:32:12.433,2023-12-31 22:01:59,2023-12-31 22:30:45,2023-12-31 23:06:41,서대문구,남가좌제2동,강북구,수유제2동,3300,16729.0,58.542783,0
1156500,2023-12-31 21:35:31.000,2023-12-31 21:36:00.000,2023-12-31 22:14:00,2023-12-31 22:23:30,2023-12-31 22:32:13,은평구,대조동,은평구,응암제1동,1500,1610.0,47.983333,0
1156501,2023-12-31 21:53:23.397,2023-12-31 21:53:23.397,2023-12-31 22:27:05,2023-12-31 22:52:04,2023-12-31 23:11:35,강서구,화곡제6동,영등포구,여의동,2600,8107.0,58.676717,0
1156502,2023-12-31 22:21:37.000,2023-12-31 22:22:00.000,2023-12-31 23:17:31,2023-12-31 23:33:47,2023-12-31 23:40:26,노원구,하계1동,노원구,중계1동,1500,1745.0,72.166667,0
1156503,2023-12-31 22:27:03.903,2023-12-31 22:27:03.903,2023-12-31 23:19:02,2023-12-31 23:33:06,2023-12-31 23:40:06,노원구,상계10동,노원구,상계9동,1500,1486.0,66.034950,0

In [ ]:
# 데이터 불러오기
file_path = "merged_boarding.csv"
data = pd.read_csv(file_path)

data

,접수일시,예정일시,배차일시,승차일시,하차일시,출발지구,출발지동,목적지구,목적지동,요금,승차거리,대기시간,공휴일
0,2021-01-01 02:25:24.000,2021-01-01 02:26:00.000,2021-01-01 02:35:36.000,2021-01-01 02:56:15.000,2021-01-01 03:32:21.000,강서구,등촌제3동,종로구,종로5.6가동,3400,17553.0,30.850000,1
1,2021-01-01 04:17:19.413,2021-01-01 04:17:19.413,2021-01-01 04:27:09.000,2021-01-01 04:50:16.000,2021-01-01 04:58:55.000,노원구,중계4동,노원구,하계1동,1500,2967.0,32.943117,1
2,2021-01-01 04:41:40.000,2021-01-01 04:42:00.000,2021-01-01 04:50:36.000,2021-01-01 05:07:33.000,2021-01-01 05:53:06.000,강동구,길동,강서구,염창동,4400,31641.0,25.883333,1
3,2021-01-01 06:43:55.170,2021-01-01 07:00:00.000,2021-01-01 07:08:35.000,2021-01-01 07:14:17.000,2021-01-01 07:18:44.000,노원구,하계1동,노원구,하계1동,1500,1106.0,30.363833,1
4,2021-01-01 07:23:14.143,2021-01-01 07:23:00.000,2021-01-01 07:28:32.000,2021-01-01 07:35:23.000,2021-01-01 07:37:32.000,노원구,하계1동,노원구,하계1동,1500,700.0,12.147617,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156499,2023-12-31 21:32:12.433,2023-12-31 21:32:12.433,2023-12-31 22:01:59,2023-12-31 22:30:45,2023-12-31 23:06:41,서대문구,남가좌제2동,강북구,수유제2동,3300,16729.0,58.542783,0
1156500,2023-12-31 21:35:31.000,2023-12-31 21:36:00.000,2023-12-31 22:14:00,2023-12-31 22:23:30,2023-12-31 22:32:13,은평구,대조동,은평구,응암제1동,1500,1610.0,47.983333,0
1156501,2023-12-31 21:53:23.397,2023-12-31 21:53:23.397,2023-12-31 22:27:05,2023-12-31 22:52:04,2023-12-31 23:11:35,강서구,화곡제6동,영등포구,여의동,2600,8107.0,58.676717,0
1156502,2023-12-31 22:21:37.000,2023-12-31 22:22:00.000,2023-12-31 23:17:31,2023-12-31 23:33:47,2023-12-31 23:40:26,노원구,하계1동,노원구,중계1동,1500,1745.0,72.166667,0
1156503,2023-12-31 22:27:03.903,2023-12-31 22:27:03.903,2023-12-31 23:19:02,2023-12-31 23:33:06,2023-12-31 23:40:06,노원구,상계10동,노원구,상계9동,1500,1486.0,66.034950,0

In [ ]:
# '승차거리'의 평균값 계산
mean_distance = data['승차거리'].mean()

# 평균값 미만인 경우만 필터링
filtered_data = data[data['승차거리'] < mean_distance]

# 결과 확인
print(filtered_data)

# CSV 파일로 저장
filtered_data.to_csv('merged_filtered_data.csv', index=False)

                            접수일시                     예정일시  \
1        2021-01-01 04:17:19.413  2021-01-01 04:17:19.413
3        2021-01-01 06:43:55.170  2021-01-01 07:00:00.000
4        2021-01-01 07:23:14.143  2021-01-01 07:23:00.000
5        2021-01-01 07:26:44.980  2021-01-01 07:26:44.980
6        2021-01-01 08:13:25.000  2021-01-01 08:14:00.000
...                          ...                      ...
1156497  2023-12-31 20:38:55.993  2023-12-31 20:39:00.000
1156498  2023-12-31 20:52:16.170  2023-12-31 20:52:16.170
1156500  2023-12-31 21:35:31.000  2023-12-31 21:36:00.000
1156502  2023-12-31 22:21:37.000  2023-12-31 22:22:00.000
1156503  2023-12-31 22:27:03.903  2023-12-31 22:27:03.903

                            배차일시                     승차일시  \
1        2021-01-01 04:27:09.000  2021-01-01 04:50:16.000
3        2021-01-01 07:08:35.000  2021-01-01 07:14:17.000
4        2021-01-01 07:28:32.000  2021-01-01 07:35:23.000
5        2021-01-01 07:35:56.000  2021-01-01 07:42:53.000
6        2021-01-01 08:17:19.000  2021-01-01 08:34:19.000
...                          ...                      ...
1156497      2023-12-31 21:29:55      2023-12-31 21:41:31
1156498      2023-12-31 21:37:25      2023-12-31 22:01:59
1156500      2023-12-31 22:14:00      2023-12-31 22:23:30
1156502      2023-12-31 23:17:31      2023-12-31 23:33:47
1156503      2023-12-31 23:19:02      2023-12-31 23:33:06

                            하차일시 출발지구   출발지동 목적지구    목적지동    요금    승차거리  \
1        2021-01-01 04:58:55.000  노원구   중계4동  노원구    하계1동  1500  2967.0
3        2021-01-01 07:18:44.000  노원구   하계1동  노원구    하계1동  1500  1106.0
4        2021-01-01 07:37:32.000  노원구   하계1동  노원구    하계1동  1500   700.0
5        2021-01-01 07:50:02.000  노원구   월계1동  노원구  상계6.7동  1500  3425.0
6        2021-01-01 08:38:10.000  강서구  화곡제3동  양천구    신월5동  1500  1505.0
...                          ...  ...    ...  ...     ...   ...     ...
1156497      2023-12-31 21:59:56  강서구  방화제2동  양천구    신월2동  2000  6885.0
1156498      2023-12-31 22:08:51  은평구  불광제1동  은평구     대조동  1500  1064.0
1156500      2023-12-31 22:32:13  은평구    대조동  은평구   응암제1동  1500  1610.0
1156502      2023-12-31 23:40:26  노원구   하계1동  노원구    중계1동  1500  1745.0
1156503      2023-12-31 23:40:06  노원구  상계10동  노원구    상계9동  1500  1486.0

              대기시간  공휴일
1        32.943117    1
3        30.363833    1
4        12.147617    1
5        16.133667    1
6        20.900000    1
...            ...  ...
1156497  62.583450    0
1156498  69.713833    0
1156500  47.983333    0
1156502  72.166667    0
1156503  66.034950    0

[795215 rows x 13 columns]

In [ ]:
mean_distance

7200.241063584735

In [ ]:
filtered_data

,접수일시,예정일시,배차일시,승차일시,하차일시,출발지구,출발지동,목적지구,목적지동,요금,승차거리,대기시간,공휴일
1,2021-01-01 04:17:19.413,2021-01-01 04:17:19.413,2021-01-01 04:27:09.000,2021-01-01 04:50:16.000,2021-01-01 04:58:55.000,노원구,중계4동,노원구,하계1동,1500,2967.0,32.943117,1
3,2021-01-01 06:43:55.170,2021-01-01 07:00:00.000,2021-01-01 07:08:35.000,2021-01-01 07:14:17.000,2021-01-01 07:18:44.000,노원구,하계1동,노원구,하계1동,1500,1106.0,30.363833,1
4,2021-01-01 07:23:14.143,2021-01-01 07:23:00.000,2021-01-01 07:28:32.000,2021-01-01 07:35:23.000,2021-01-01 07:37:32.000,노원구,하계1동,노원구,하계1동,1500,700.0,12.147617,1
5,2021-01-01 07:26:44.980,2021-01-01 07:26:44.980,2021-01-01 07:35:56.000,2021-01-01 07:42:53.000,2021-01-01 07:50:02.000,노원구,월계1동,노원구,상계6.7동,1500,3425.0,16.133667,1
6,2021-01-01 08:13:25.000,2021-01-01 08:14:00.000,2021-01-01 08:17:19.000,2021-01-01 08:34:19.000,2021-01-01 08:38:10.000,강서구,화곡제3동,양천구,신월5동,1500,1505.0,20.900000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1156497,2023-12-31 20:38:55.993,2023-12-31 20:39:00.000,2023-12-31 21:29:55,2023-12-31 21:41:31,2023-12-31 21:59:56,강서구,방화제2동,양천구,신월2동,2000,6885.0,62.583450,0
1156498,2023-12-31 20:52:16.170,2023-12-31 20:52:16.170,2023-12-31 21:37:25,2023-12-31 22:01:59,2023-12-31 22:08:51,은평구,불광제1동,은평구,대조동,1500,1064.0,69.713833,0
1156500,2023-12-31 21:35:31.000,2023-12-31 21:36:00.000,2023-12-31 22:14:00,2023-12-31 22:23:30,2023-12-31 22:32:13,은평구,대조동,은평구,응암제1동,1500,1610.0,47.983333,0
1156502,2023-12-31 22:21:37.000,2023-12-31 22:22:00.000,2023-12-31 23:17:31,2023-12-31 23:33:47,2023-12-31 23:40:26,노원구,하계1동,노원구,중계1동,1500,1745.0,72.166667,0
1156503,2023-12-31 22:27:03.903,2023-12-31 22:27:03.903,2023-12-31 23:19:02,2023-12-31 23:33:06,2023-12-31 23:40:06,노원구,상계10동,노원구,상계9동,1500,1486.0,66.034950,0